# Generated by Django 3.2.7 on 2021-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vehicles',
            field=models.ManyToManyField(help_text='Set of vehicles that this person has piloted.', null=True, to='people.Vehicle'),
        ),
    ]
