# Generated by Django 3.2.7 on 2021-09-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this planet.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this species.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this vehicle.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this person.', max_length=50)),
                ('birth_year', models.CharField(help_text='The birth year of the person, \n    using the in-universe standard of BBY or ABY - Before the Battle of Yavin or After the Battle of Yavin. \n    The Battle of Yavin is a battle that occurs at the end of Star Wars episode IV: A New Hope.', max_length=10)),
                ('eye_color', models.CharField(help_text='The eye color of this person. Will be "unknown" \n    if not known or "n/a" if the person does not have an eye.', max_length=10)),
                ('hair_color', models.CharField(help_text='The hair color of this person. Will be "unknown" \n    if not known or "n/a" if the person does not have hair.', max_length=10)),
                ('skin_color', models.CharField(help_text='The skin color of this person.', max_length=10)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.planet')),
                ('species', models.ManyToManyField(help_text='Set of species that this person belongs to.', to='people.Species')),
                ('vehicles', models.ManyToManyField(help_text='Set of vehicles that this person has piloted.', to='people.Vehicle')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
