# Generated by Django 3.2.7 on 2021-09-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='eye_color',
            field=models.CharField(help_text='The eye color of this person. Will be "unknown" \n    if not known or "n/a" if the person does not have an eye.', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='hair_color',
            field=models.CharField(help_text='The hair color of this person. Will be "unknown" \n    if not known or "n/a" if the person does not have hair.', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='skin_color',
            field=models.CharField(help_text='The skin color of this person.', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Set of vehicles that this person has piloted.', null=True, to='people.Vehicle'),
        ),
    ]
