# Generated by Django 3.2.7 on 2021-09-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20210917_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='eye_color',
            field=models.CharField(help_text='The eye color of this person. Should be "unknown" \n    if not known or "n/a" if the person does not have an eye.', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='hair_color',
            field=models.CharField(help_text='The hair color of this person. Should be "unknown" \n    if not known or "n/a" if the person does not have hair.', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='homeworld',
            field=models.ForeignKey(help_text='Planet that this person was born on or inhabits.', on_delete=django.db.models.deletion.PROTECT, to='people.planet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='The name of this person.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(help_text='The name of this planet.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='The name of this species.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(help_text='The name of this vehicle.', max_length=50, unique=True),
        ),
    ]
